trigger:

  - main

pool: 'Default'

variables:
   - group: sachin

steps:
  
  - script: | 
     python3 -m venv env
     source env/bin/activate
     pip install databricks-cli
     databricks --version

  - script: |
     DATABRICKS_AAD_TOKEN=$(Accesskey)
     exoprt DATABRICKS_AAD_TOKEN
     echo $(WorkspaceUrl) | databricks configure --aad-token
    displayName: 'logged into databricks'
     

  - script: |  
     databricks workspace import --language PYTHON -o my_notebook.py /sacnotebook.py
     ls
     pwd
    displayName: 'added notebook'  

  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: /home/sigmoid/myagent/workdir/2/s
     ArtifactName: 'drop'
     publishLocation: 'Container'
