trigger:

  - main

pool: 'Default'

variables:
   - group: sachin

steps:
  
  - script: | 
     python3 -m venv env
     source env/bin/activate
     pip install databricks-cli
     databricks --version
     exoprt DATABRICKS_AAD_TOKEN='$(Accesskey)'
     echo $(WorkspaceUrl) | databricks configure --aad-token 
     databricks workspace import --language PYTHON -o my_notebook.py /sacnotebook.py
    displayName: 'added notebook'  

  - task: CopyPublishBuildArtifacts@1
    inputs:
      CopyRoot: $(Build.ArtifactStagingDirectory)
      Contents: '**'
      ArtifactName: 'databricks'
      ArtifactType: 'Container'
     
  
