trigger:

  - main

pool: 'Default'

variables:
   - group: sachin

steps:
  
  - script: | 
     python3 -m venv env
     source env/bin/activate
     pip install databricks-cli
     databricks --version
     databricks workspace import --language PYTHON -o my_notebook.py /sacnotebook.py
    displayName: 'added notebook' 


  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)/my_notebook.py'
     ArtifactName: 'drop'
     publishLocation: 'Container'
  
