trigger:
  - main

pool: 'Default'

variables:
  - name: DATABRICKS_ACCESS_TOKEN
    value: $(Accesskey)
  - name: DATABRICKS_WORKSPACE_URL
    value: $(WorkspaceUrl)
  - name: DATABRICKS_CLUSTER_ID
    value: $(ClusterId)
  - name: GITHUB_TOKEN 
    value: $(github_token)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11.2'
      architecture: 'x64' 
      addToPath: true
      TOKEN: "$(GITHUB_TOKEN)"

  - script: |
      python -m pip install databricks-cli
      databricks configure --token "$(DATABRICKS_ACCESS_TOKEN)" --url "$(DATABRICKS_WORKSPACE_URL)"
  - task: Bash@3
    inputs:
       targetType: 'inline'
       script: |
         databricks workspace import --format SOURCE --language PYTHON --overwrite '/HelloWorld' << EOF
         print("Hello, World!")
         EOF

  - task: Bash@3
    inputs:
       targetType: 'inline'
       script: |
         databricks runs submit --json '{ "notebook_path": "/HelloWorld" }' --cluster-id "$(DATABRICKS_CLUSTER_ID)"
