trigger:

  - main

pool: 'Default'

variables:
   - group: sachin

steps:
  
  - script: | 
     python3 -m venv env
     source env/bin/activate
     pip install databricks-cli
     databricks --version

  - script: |
     exoprt DATABRICKS_AAD_TOKEN=='$(Accesskey)'
     echo $(WorkspaceUrl) | databricks configure --aad-token
    displayName: 'logged into databricks'
     

  - script: |  
     databricks workspace import --language PYTHON -o my_notebook.py /sacnotebook.py
     ls
     pwd
     echo '$(Build.ArtifactStagingDirectory)'
    displayName: 'added notebook'  

  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
     ArtifactName: 'drop'
     publishLocation: 'Container'
